services:
  fastapi:
    build: ./
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app
    restart: unless-stopped
    
  postgres-source:
    image: postgres
    container_name: postgres-source-db
    hostname: postgressourcehost
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_SOURCE_DB}
    ports:
      - ${POSTGRES_SOURCE_PORT}:5432
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-target:
    image: postgres
    container_name: postgres-target-db
    hostname: postgrestargethost
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_TARGET_PORT}:5432
    volumes:
      - postgres_target_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_HOST=postgreshost
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_SOURCE_DB}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres-source
      - postgres-target
    volumes:
      -  ./entrypoint.sh:/entrypoint_custom.sh
    user: root

volumes:
  postgres_source_data:
  postgres_target_data: